image: kisel/meteor-imagemagick-onbuild

before_script:
  - meteor npm i

stages:
  - build
  - test
  - deploy

test-build:
  stage: build
  script: meteor test --unsafe-perm --driver-package practicalmeteor:mocha
